services:
  - type: web
    name: rhd-backend
    runtime: node
    buildCommand: npx prisma migrate deploy && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production