services:
  nginx:
    image: nginx:1.27-alpine
    container_name: rhd-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    depends_on:
      - api
    networks:
      - rhd

  certbot:
    image: certbot/certbot
    container_name: rhd-certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    entrypoint: >
      /bin/sh -c "trap exit TERM; while :; do
      certbot renew --webroot -w /var/www/certbot
      --email raselhossaindev7@gmail.com --agree-tos --no-eff-email
      -d api.raselhossain.dev
      sleep 12h & wait $${!}; done;"
    networks:
      - rhd

  api:
    image: rhd-backend:latest
    container_name: rhd-api
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      NODE_ENV: production
    expose:
      - "5000"
    networks:
      - rhd

networks:
  rhd:
    driver: bridge

volumes:
  certbot_www:
  certbot_conf: