import { PrismaClient, Prisma } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding database...");

  // Create admin user
  const hashedPassword = await bcrypt.hash("Admin123@@", 12);
  const admin = await prisma.user.upsert({
    where: { email: "raselhossain86666@gmail.com" },
    update: {},
    create: {
      email: "raselhossain86666@gmail.com",
      name: "Rasel Hossain",
      password: hashedPassword,
      role: "ADMIN",
    },
  });
  console.log("✅ Admin user created:", admin.email);

  // ─── Projects ──────────────────────────────────────────
  const projects = [
    {
      slug: "bfs-mart",
      title: "BFS Mart",
      subtitle: "E-commerce platform",
      category: "E-commerce",
      description: "Full e-commerce experience with catalog, cart, checkout, payments and admin panel -- fast and SEO-friendly.",
      role: "Full-stack development & architecture",
      problem: "The business was selling through social media and phone calls -- no real storefront, manual order tracking and no payment flow.",
      approach: "Built a Next.js storefront with a Node.js API and PostgreSQL. Added Stripe checkout, an admin panel for orders and inventory, SEO-optimized product pages and Cloudflare CDN in front.",
      outcome: "The new store handles the full catalog, checkout and order administration. Pages load dramatically faster than the previous flow and the team stopped managing orders by hand.",
      year: "2025",
      gradient: "from-violet-600 via-purple-600 to-fuchsia-600",
      featured: true,
      order: 1,
      highlights: ["Stripe-powered checkout with order state management", "Admin panel for products, inventory and orders", "SEO + Core Web Vitals-friendly product pages", "Cloudflare CDN and caching for fast global loads"],
      quote: { text: "Orders used to come through phone calls and DMs -- now the whole store runs itself online.", source: "Store owner" },
      metrics: [{ value: "<1.5s", label: "avg page load" }, { value: "100%", label: "orders online" }, { value: "24/7", label: "live storefront" }],
      technologies: [{ name: "Next.js" }, { name: "Node.js" }, { name: "PostgreSQL" }, { name: "Stripe" }],
      metaTitle: "BFS Mart - E-commerce Platform Case Study | Rasel Hossain",
      metaDescription: "Full e-commerce platform with catalog, cart, checkout, Stripe payments and admin panel. Built with Next.js, Node.js and PostgreSQL.",
      keywords: ["e-commerce platform", "Next.js e-commerce", "Stripe checkout", "online store", "full stack e-commerce"],
      geoRegion: "BD-DH", geoPlaceName: "Dhaka", geoPosition: "23.8103;90.4125", geoCountry: "Bangladesh", areaServed: "Worldwide",
      faqJson: [
        { question: "What technologies were used for BFS Mart?", answer: "Next.js for the frontend, Node.js for the API, PostgreSQL for the database, Stripe for payments, and Cloudflare for CDN and caching." },
        { question: "How fast does the BFS Mart storefront load?", answer: "Average page load is under 1.5 seconds thanks to server-side rendering, optimized images, and Cloudflare CDN caching." },
      ],
      howToSteps: [
        { name: "Discovery", text: "Analyzed the business's existing sales process and identified pain points in order management." },
        { name: "Architecture", text: "Designed a Next.js + Node.js + PostgreSQL stack with Stripe integration for payments." },
        { name: "Development", text: "Built the storefront, admin panel, and order management system with real-time inventory tracking." },
        { name: "Deployment", text: "Deployed with Cloudflare CDN, SSL, and performance monitoring for global fast loads." },
      ],
      speakableText: "BFS Mart e-commerce platform built by Rasel Hossain. Full-stack development with Next.js, Node.js, PostgreSQL and Stripe.",
    },
    {
      slug: "medexa-one",
      title: "Medexa One",
      subtitle: "Healthcare platform",
      category: "Healthcare",
      description: "Business platform with complex architecture: Next.js frontend, NestJS backend, PostgreSQL and queue-based processing.",
      role: "Architecture & full-stack development",
      problem: "The healthcare business needed a platform that could grow -- reliable data handling, background jobs and clean separation between services.",
      approach: "Drove the system architecture: Next.js frontend, NestJS modular API, PostgreSQL with migrations, and queue-based workers for heavy background work. Auth with OTP flows.",
      outcome: "Production-ready architecture that handled real load from day one, with background processing isolated into workers so request paths stay fast.",
      year: "2025",
      gradient: "from-cyan-500 via-sky-600 to-blue-600",
      featured: true,
      order: 2,
      highlights: ["Modular NestJS API with clean service boundaries", "Queue + worker layer for background processing", "PostgreSQL schema and migration workflow", "OTP-based authentication flows"],
      quote: { text: "The architecture held up from day one -- heavy jobs run in the background without slowing the app.", source: "Platform lead" },
      metrics: [{ value: "3", label: "service layers" }, { value: "0", label: "downtime day one" }, { value: "24/7", label: "background workers" }],
      technologies: [{ name: "Next.js" }, { name: "NestJS" }, { name: "PostgreSQL" }, { name: "Queues" }],
      metaTitle: "Medexa One - Healthcare Platform Case Study | Rasel Hossain",
      metaDescription: "Healthcare platform with Next.js frontend, NestJS backend, PostgreSQL and queue-based processing. Architecture & full-stack development.",
      keywords: ["healthcare platform", "NestJS backend", "queue processing", "Next.js healthcare", "full stack developer Bangladesh"],
      geoRegion: "BD-DH", geoPlaceName: "Dhaka", geoPosition: "23.8103;90.4125", geoCountry: "Bangladesh", areaServed: "Worldwide",
      faqJson: [
        { question: "Why was NestJS chosen for Medexa One?", answer: "NestJS provides modular architecture with clean service boundaries, making it ideal for complex healthcare systems that need isolation between different business domains." },
        { question: "How does the queue system work?", answer: "Heavy background tasks like report generation, data processing, and notifications are pushed to a queue and processed by dedicated workers, keeping the main API fast." },
      ],
      howToSteps: [
        { name: "System Design", text: "Mapped the healthcare workflows and designed a modular architecture with clear service boundaries." },
        { name: "Backend Build", text: "Built the NestJS API with PostgreSQL, migrations, OTP auth, and queue-based workers." },
        { name: "Frontend Build", text: "Developed the Next.js frontend with responsive design and real-time data updates." },
        { name: "Testing & Deploy", text: "Load tested the system, verified queue processing, and deployed with monitoring." },
      ],
      speakableText: "Medexa One healthcare platform by Rasel Hossain. Built with Next.js, NestJS, PostgreSQL and queue-based processing.",
    },
    {
      slug: "visa-master-bd",
      title: "Visa Master BD",
      subtitle: "Business website with lead automation",
      category: "Automation",
      description: "Client-facing website with lead capture automation and intelligent notification flows for the business team.",
      role: "Full-stack development & automation",
      problem: "Enquiries arrived through multiple channels and sat in inboxes -- slow responses, lost leads and no way to track follow-ups.",
      approach: "Built an SEO-friendly Next.js site with lead-capture forms wired to an automation pipeline (Supabase + n8n-style flows) and instant notifications to the right team members.",
      outcome: "Leads now land in a structured flow and reach the responsible person immediately -- nothing gets lost and the team saves hours of manual triage every week.",
      year: "2024",
      gradient: "from-emerald-500 via-teal-600 to-cyan-600",
      featured: true,
      order: 3,
      highlights: ["Lead capture with validation and deduplication", "Automated routing + instant team notifications", "Supabase-backed storage and tracking", "Cloudflare-protected, fast static delivery"],
      quote: { text: "Every enquiry now lands with the right person instantly. Nothing sits in an inbox anymore.", source: "Business owner" },
      metrics: [{ value: "0", label: "lost leads" }, { value: "Instant", label: "lead routing" }, { value: "Hours", label: "saved / week" }],
      technologies: [{ name: "Next.js" }, { name: "Supabase" }, { name: "AI automation" }, { name: "Cloudflare" }],
      metaTitle: "Visa Master BD - Lead Automation Case Study | Rasel Hossain",
      metaDescription: "Business website with lead capture automation, Supabase storage and instant notifications. Built with Next.js and n8n-style flows.",
      keywords: ["lead automation", "n8n automation", "Supabase", "Next.js business site", "lead capture system"],
      geoRegion: "BD-DH", geoPlaceName: "Dhaka", geoPosition: "23.8103;90.4125", geoCountry: "Bangladesh", areaServed: "Worldwide",
      faqJson: [
        { question: "How does the lead automation work?", answer: "Leads from website forms are captured, validated, deduplicated, and routed to the right team member instantly via automated notification flows." },
        { question: "What is n8n and how is it used?", answer: "n8n is a workflow automation tool. It connects the lead capture forms to storage, notifications, and follow-up sequences without manual intervention." },
      ],
      howToSteps: [
        { name: "Audit", text: "Mapped all lead sources and identified where enquiries were getting lost." },
        { name: "Automation Design", text: "Designed the lead capture, validation, routing, and notification pipeline." },
        { name: "Build", text: "Built the Next.js site with forms, Supabase storage, and n8n automation flows." },
        { name: "Launch", text: "Deployed with Cloudflare protection and verified lead routing end-to-end." },
      ],
      speakableText: "Visa Master BD lead automation by Rasel Hossain. Next.js website with Supabase and automated lead routing.",
    },
    {
      slug: "wedding-collection",
      title: "Wedding Collection",
      subtitle: "E-commerce store",
      category: "E-commerce",
      description: "Product-focused storefront with inventory, ordering workflow and payment integration for a wedding retail business.",
      role: "Full-stack development",
      problem: "A wedding retail business needed a product storefront fast -- inventory visibility, clear ordering and payments without a heavy platform.",
      approach: "Shipped a Next.js storefront with MongoDB product data, an ordering workflow and payment integration, deployed behind Nginx.",
      outcome: "The store became the operational front door -- customers browse stock, place orders and pay online while the team manages inventory from the admin side.",
      year: "2024",
      gradient: "from-pink-500 via-rose-600 to-red-600",
      featured: false,
      order: 4,
      highlights: ["Product catalog with live inventory status", "Guided ordering workflow", "Payment integration", "Nginx + SSL production deployment"],
      quote: Prisma.JsonNull,
      metrics: [{ value: "Live", label: "inventory status" }, { value: "Online", label: "payments" }, { value: "SSL", label: "secure checkout" }],
      technologies: [{ name: "Next.js" }, { name: "MongoDB" }, { name: "Payments" }, { name: "Nginx" }],
      metaTitle: "Wedding Collection - E-commerce Store Case Study | Rasel Hossain",
      metaDescription: "Product-focused e-commerce storefront with inventory management, ordering workflow and payment integration. Built with Next.js and MongoDB.",
      keywords: ["e-commerce store", "wedding retail", "Next.js store", "MongoDB e-commerce", "product catalog"],
      geoRegion: "BD-DH", geoPlaceName: "Dhaka", geoPosition: "23.8103;90.4125", geoCountry: "Bangladesh", areaServed: "Worldwide",
      faqJson: [
        { question: "Why MongoDB for this project?", answer: "MongoDB's flexible document model was ideal for the product catalog with varying attributes across different wedding product categories." },
      ],
      howToSteps: [
        { name: "Requirements", text: "Defined the product catalog structure, ordering workflow, and payment requirements." },
        { name: "Build", text: "Developed the Next.js storefront with MongoDB, inventory management, and payment integration." },
        { name: "Deploy", text: "Deployed behind Nginx with SSL, configured for production traffic." },
      ],
      speakableText: "Wedding Collection e-commerce store by Rasel Hossain. Built with Next.js, MongoDB and payment integration.",
    },
    {
      slug: "villarreal-cf",
      title: "Villarreal CF",
      subtitle: "Football club web platform",
      category: "Web Platform",
      description: "Club web platform project featuring rich content, responsive design and strong performance.",
      role: "Frontend development",
      problem: "A club web platform needed to present rich content -- news, teams and media -- with responsive layouts and fast loading across devices.",
      approach: "Built with Next.js and Tailwind CSS on a headless CMS, focusing on responsive design, content organization and performance budgets.",
      outcome: "A polished, responsive platform with structured content delivery and solid performance across mobile and desktop.",
      year: "2023",
      gradient: "from-amber-500 via-orange-600 to-rose-600",
      featured: false,
      order: 5,
      highlights: ["Headless CMS content model", "Responsive, mobile-first layouts", "Performance-focused delivery"],
      quote: Prisma.JsonNull,
      metrics: [{ value: "Mobile-first", label: "responsive" }, { value: "Fast", label: "page loads" }],
      technologies: [{ name: "Next.js" }, { name: "Tailwind CSS" }, { name: "Headless CMS" }],
      metaTitle: "Villarreal CF - Football Club Platform Case Study | Rasel Hossain",
      metaDescription: "Football club web platform with headless CMS, responsive design and performance optimization. Built with Next.js and Tailwind CSS.",
      keywords: ["football club website", "headless CMS", "Next.js sports", "responsive web design", "Tailwind CSS"],
      geoRegion: "BD-DH", geoPlaceName: "Dhaka", geoPosition: "23.8103;90.4125", geoCountry: "Bangladesh", areaServed: "Worldwide",
      faqJson: [
        { question: "What CMS was used for Villarreal CF?", answer: "A headless CMS was used to manage content (news, teams, media) which is then delivered via API to the Next.js frontend for optimal performance." },
      ],
      howToSteps: [
        { name: "Content Model", text: "Designed the headless CMS content model for news, teams, and media sections." },
        { name: "Frontend Build", text: "Built the Next.js frontend with Tailwind CSS, focusing on responsive layouts and performance." },
        { name: "Integration", text: "Connected the headless CMS API and optimized content delivery with caching." },
      ],
      speakableText: "Villarreal CF football club platform by Rasel Hossain. Built with Next.js, Tailwind CSS and headless CMS.",
    },
    {
      slug: "lms-school-management",
      title: "Custom LMS & School Management",
      subtitle: "Education platform",
      category: "Education",
      description: "LMS / school management system with student, teacher and admin flows, Python workers and automated processing.",
      role: "Full-stack development & systems",
      problem: "A school needed one system for students, teachers and administration -- classes, attendance, results and reporting that used to run on paper and spreadsheets.",
      approach: "Designed role-based flows for students, teachers and admins on a Next.js + NestJS stack with PostgreSQL, plus Python workers for bulk and scheduled processing.",
      outcome: "Academic and administrative workflows moved into one platform -- records are centralized and scheduled jobs automate recurring reporting and processing.",
      year: "2023",
      gradient: "from-indigo-500 via-blue-600 to-violet-600",
      featured: false,
      order: 6,
      highlights: ["Student / teacher / admin role flows", "Python workers for scheduled processing", "Centralized records and reporting"],
      quote: { text: "Attendance, results and reporting finally live in one system instead of spreadsheets.", source: "School administrator" },
      metrics: [{ value: "3", label: "role flows" }, { value: "Auto", label: "recurring reports" }, { value: "1", label: "source of truth" }],
      technologies: [{ name: "Next.js" }, { name: "NestJS" }, { name: "Python workers" }, { name: "PostgreSQL" }],
      metaTitle: "Custom LMS & School Management - Education Platform Case Study | Rasel Hossain",
      metaDescription: "LMS and school management system with student, teacher and admin flows. Built with Next.js, NestJS, PostgreSQL and Python workers.",
      keywords: ["school management system", "LMS development", "education platform", "Next.js LMS", "student management"],
      geoRegion: "BD-DH", geoPlaceName: "Dhaka", geoPosition: "23.8103;90.4125", geoCountry: "Bangladesh", areaServed: "Worldwide",
      faqJson: [
        { question: "What roles does the LMS support?", answer: "Three role flows: students (attendance, results, assignments), teachers (grading, class management), and admins (reporting, configuration, user management)." },
        { question: "Why Python workers for a Node.js project?", answer: "Python workers handle bulk data processing, scheduled reports, and heavy computational tasks that run independently from the main API." },
      ],
      howToSteps: [
        { name: "Requirements", text: "Interviewed school staff to map student, teacher, and admin workflows." },
        { name: "Architecture", text: "Designed role-based access, PostgreSQL schema, and Python worker architecture." },
        { name: "Build", text: "Developed the Next.js frontend, NestJS API, and Python processing workers." },
        { name: "Deploy", text: "Deployed the full system with scheduled jobs and monitoring." },
      ],
      speakableText: "Custom LMS and school management system by Rasel Hossain. Built with Next.js, NestJS, PostgreSQL and Python workers.",
    },
  ];

  for (const project of projects) {
    const { technologies, metrics, ...rest } = project;
    const technologyData = technologies.map((t) => ({ name: t.name }));
    const metricData = metrics.map((m) => ({ value: m.value, label: m.label }));

    await prisma.project.upsert({
      where: { slug: project.slug },
      update: {
        ...rest,
        technologies: { deleteMany: {}, create: technologyData },
        metrics: { deleteMany: {}, create: metricData },
      },
      create: {
        ...rest,
        technologies: { create: technologyData },
        metrics: { create: metricData },
      },
    });
  }
  console.log("✅ Projects seeded");

  // ─── Blog Posts ──────────────────────────────────────────
  const posts = [
    {
      slug: "nextjs-16-server-components",
      title: "What's new in Next.js 16 server components",
      category: "Next.js",
      excerpt: "Async params, cache components and the death of sync dynamic APIs — a practical tour of the biggest changes.",
      content: "Next.js 16 ships with a major cleanup: synchronous dynamic APIs are gone, params are promises, and the middleware concept has been renamed to proxy. Server components remain the default way to fetch data, and the new cache components make partial caching much more explicit and composable.",
      readTime: "6 min read",
      date: new Date("2026-07-02"),
      published: true,
      tags: ["Next.js", "React"],
      keywords: ["Next.js 16", "server components", "React", "Next.js server components", "async params", "cache components"],
      geoRegion: "BD-DH",
      geoPlaceName: "Dhaka",
      geoPosition: "23.8103;90.4125",
      geoCountry: "Bangladesh",
      metaTitle: "What's new in Next.js 16 server components | Rasel Hossain",
      metaDescription: "A practical guide to Next.js 16 server components: async params, cache components, and the removal of sync dynamic APIs.",
      faqJson: [
        { question: "What changed in Next.js 16 server components?", answer: "Synchronous dynamic APIs are removed, params are now promises, middleware is renamed to proxy, and new cache components provide explicit caching." },
        { question: "Do I need to rewrite my app for Next.js 16?", answer: "Most apps need minimal changes. The biggest updates are replacing sync dynamic API calls and updating middleware to the new proxy format." },
      ],
      howToSteps: [
        { name: "Update Next.js", text: "Run npm install next@latest to get Next.js 16." },
        { name: "Replace sync APIs", text: "Replace any synchronous dynamic API calls with their async equivalents." },
        { name: "Migrate middleware", text: "Rename your middleware file to proxy and update the export syntax." },
        { name: "Use cache components", text: "Import and use the new cache components for explicit partial caching." },
      ],
      speakableText: "Next.js 16 server components guide by Rasel Hossain. Learn about async params, cache components, and the removal of sync dynamic APIs.",
    },
    {
      slug: "practical-ai-automation",
      title: "Practical AI automation for business teams",
      category: "AI",
      excerpt: "Where AI adds real business value, how to combine n8n, APIs and LLMs safely — and where to skip it.",
      content: "The best AI automations are boring: they take a repetitive, well-defined workflow and remove the manual steps. Lead handling, document processing, notifications and data entry are classic candidates. A solid pattern is API + database + AI + queue: external webhooks feed a worker, an LLM classifies or extracts, results land in the database, and notifications go out automatically.",
      readTime: "7 min read",
      date: new Date("2026-05-18"),
      published: true,
      tags: ["AI", "Automation", "n8n"],
      keywords: ["AI automation", "n8n", "business automation", "LLM", "workflow automation", "API integration"],
      geoRegion: "BD-DH",
      geoPlaceName: "Dhaka",
      geoPosition: "23.8103;90.4125",
      geoCountry: "Bangladesh",
      metaTitle: "Practical AI automation for business teams | Rasel Hossain",
      metaDescription: "Learn where AI adds real business value and how to combine n8n, APIs and LLMs safely for workflow automation.",
      faqJson: [
        { question: "What are the best use cases for AI automation?", answer: "Lead handling, document processing, notifications, data entry, and customer support triage are classic candidates where AI automation adds real value." },
        { question: "What tools do you use for AI automation?", answer: "I primarily use n8n for workflow orchestration, combined with OpenAI/Anthropic LLMs for classification and extraction, and webhooks for integration." },
      ],
      howToSteps: [
        { name: "Identify repetitive tasks", text: "Map out workflows where humans do the same steps repeatedly." },
        { name: "Set up n8n", text: "Install n8n and create a workflow with webhook triggers." },
        { name: "Add AI classification", text: "Connect an LLM node to classify or extract data from incoming records." },
        { name: "Automate notifications", text: "Add notification nodes to alert teams when automation completes." },
      ],
      speakableText: "Practical AI automation guide by Rasel Hossain. Learn where AI adds business value and how to combine n8n, APIs and LLMs safely.",
    },
    {
      slug: "design-systems-with-tailwind",
      title: "Building design systems with Tailwind CSS v4",
      category: "Design",
      excerpt: "From CSS variables and theme tokens to component APIs — how to standardize products under one system.",
      content: "Tailwind v4 moves configuration into CSS with @theme, which means design tokens live next to your other styles instead of a config file. This allows a shared token layer — colors, spacing, radii and typography — and composable primitives on top. The result: consistent UI with a single source of truth. The system pays for itself quickly. New features ship faster, and design reviews focus on behavior instead of spacing.",
      readTime: "6 min read",
      date: new Date("2026-03-09"),
      published: true,
      tags: ["Tailwind CSS", "Design Systems"],
      keywords: ["Tailwind CSS v4", "design systems", "CSS variables", "theme tokens", "component API", "UI consistency"],
      geoRegion: "BD-DH",
      geoPlaceName: "Dhaka",
      geoPosition: "23.8103;90.4125",
      geoCountry: "Bangladesh",
      metaTitle: "Building design systems with Tailwind CSS v4 | Rasel Hossain",
      metaDescription: "Learn how to build scalable design systems with Tailwind CSS v4 using CSS variables, theme tokens and composable component APIs.",
      faqJson: [
        { question: "What is new in Tailwind CSS v4 for design systems?", answer: "Tailwind v4 moves configuration into CSS with @theme, allowing design tokens to live alongside your styles for a single source of truth." },
        { question: "How do design systems improve development speed?", answer: "Design systems provide reusable primitives and tokens, so new features ship faster and design reviews focus on behavior instead of spacing." },
      ],
      howToSteps: [
        { name: "Define tokens", text: "Create a CSS file with @theme to define your design tokens (colors, spacing, radii)." },
        { name: "Build primitives", text: "Create composable component primitives that consume the tokens." },
        { name: "Document usage", text: "Write guidelines for when and how to use each primitive." },
        { name: "Enforce consistency", text: "Use linting rules to prevent direct token access outside components." },
      ],
      speakableText: "Building design systems with Tailwind CSS v4 by Rasel Hossain. Learn CSS variables, theme tokens and composable component APIs.",
    },
    {
      slug: "performance-budget-checklist",
      title: "A practical performance budget checklist",
      category: "Performance",
      excerpt: "The checks I run before any site goes to production — from bundle budgets to Core Web Vitals.",
      content: "Performance is a feature you have to protect. I keep a checklist that takes about 30 minutes to run and catches 90% of regressions. The essentials: set an explicit bundle budget, watch your largest image, lazy-load below-the-fold media, and always measure with real device profiles — not just desktop Chrome. Reviewing the checklist every sprint keeps perf discussions concrete and prevents the slow creep that makes sites feel heavy a year later.",
      readTime: "5 min read",
      date: new Date("2026-01-22"),
      published: true,
      tags: ["Performance", "Web Vitals"],
      keywords: ["performance budget", "Core Web Vitals", "web performance", "bundle size", "Lighthouse", "page speed"],
      geoRegion: "BD-DH",
      geoPlaceName: "Dhaka",
      geoPosition: "23.8103;90.4125",
      geoCountry: "Bangladesh",
      metaTitle: "A practical performance budget checklist | Rasel Hossain",
      metaDescription: "A practical checklist for web performance: bundle budgets, Core Web Vitals, lazy loading and real device profiling.",
      faqJson: [
        { question: "What is a performance budget?", answer: "A performance budget is a set of limits on metrics like bundle size, load time, and Core Web Vitals that your team agrees to maintain." },
        { question: "How often should I run a performance check?", answer: "Run the checklist before every production deployment and at least once per sprint to catch regressions early." },
      ],
      howToSteps: [
        { name: "Set bundle budget", text: "Define maximum JavaScript and CSS bundle sizes in your build config." },
        { name: "Profile images", text: "Audit the largest images and compress or lazy-load below-the-fold media." },
        { name: "Measure on real devices", text: "Use Lighthouse with mobile throttling to simulate real user conditions." },
        { name: "Review every sprint", text: "Add performance review to your sprint checklist to prevent slow creep." },
      ],
      speakableText: "Performance budget checklist by Rasel Hossain. Bundle budgets, Core Web Vitals, lazy loading and real device profiling.",
    },
    {
      slug: "fullstack-architecture-pattern",
      title: "A full-stack architecture that survives year two",
      category: "Architecture",
      excerpt: "Frontend, API, database, queues, workers and deployment — how to structure a system that stays maintainable.",
      content: "Most projects don't die from bad code — they die from tangled dependencies. Separate the layers early: UI, API, domain logic, data access and infrastructure. Add a queue and a worker the moment you see background work, even trivial jobs. It keeps request paths fast and makes future scaling a configuration change instead of a rewrite. Deployment matters as much as code: containerize, keep a repeatable setup (Nginx, PM2, SSL), and monitor from day one.",
      readTime: "8 min read",
      date: new Date("2025-11-14"),
      published: true,
      tags: ["Architecture", "NestJS", "PostgreSQL"],
      keywords: ["full stack architecture", "system design", "NestJS", "PostgreSQL", "microservices", "deployment"],
      geoRegion: "BD-DH",
      geoPlaceName: "Dhaka",
      geoPosition: "23.8103;90.4125",
      geoCountry: "Bangladesh",
      metaTitle: "A full-stack architecture that survives year two | Rasel Hossain",
      metaDescription: "Learn how to structure a full-stack system that stays maintainable: frontend, API, database, queues, workers and deployment.",
      faqJson: [
        { question: "What are the key layers of a full-stack architecture?", answer: "The key layers are UI (frontend), API (routes/controllers), domain logic (services), data access (repositories/ORM), and infrastructure (deployment, queues, caching)." },
        { question: "When should I add a queue to my project?", answer: "Add a queue the moment you see background work, even trivial jobs. It keeps request paths fast and makes future scaling a configuration change." },
      ],
      howToSteps: [
        { name: "Separate layers", text: "Create distinct directories for UI, API, domain logic, data access and infrastructure." },
        { name: "Add a queue early", text: "Set up a message queue (Redis/RabbitMQ) for background jobs from day one." },
        { name: "Containerize", text: "Write a Dockerfile and docker-compose.yml for reproducible deployments." },
        { name: "Monitor from day one", text: "Add logging, error tracking and health checks before launching." },
      ],
      speakableText: "Full-stack architecture guide by Rasel Hossain. Learn how to structure frontend, API, database, queues, workers and deployment for long-term maintainability.",
    },
  ];

  for (const post of posts) {
    const { tags, ...rest } = post;
    const tagData = tags.map((name) => ({
      where: { name },
      create: { name },
    }));

    await prisma.post.upsert({
      where: { slug: post.slug },
      update: { ...rest, tags: { connectOrCreate: tagData } },
      create: { ...rest, tags: { connectOrCreate: tagData } },
    });
  }
  console.log("✅ Blog posts seeded (5 with full SEO/GEO/FAQ)");

  // ─── Services ──────────────────────────────────────────
  const services = [
    {
      slug: "full-stack-saas-development",
      icon: "code",
      title: "Full Stack & SaaS Development",
      category: "Web & SaaS",
      description: "Custom web applications, SaaS platforms, dashboards and management systems — architected to scale from day one.",
      overview: "Your product, from database schema to polished UI — designed, built and deployed as one system. I focus on architecture that stays fast and maintainable as it grows: clean API contracts, proper auth and roles, and an admin experience your team will actually enjoy using.",
      order: 1,
      featured: true,
      deliverables: ["Custom web app or SaaS MVP", "Auth, roles & admin panel", "REST/GraphQL API + database design", "Testing, deployment & handover docs"],
      stack: ["Next.js", "NestJS", "PostgreSQL", "Docker"],
      bestFor: ["Startups validating a SaaS idea", "Companies replacing spreadsheet workflows", "Teams needing internal tools & dashboards"],
      features: ["Custom web apps & internal tools", "SaaS platforms with auth & billing", "Admin dashboards & analytics", "REST & GraphQL API design"],
      metaTitle: "Full Stack & SaaS Development Services | Rasel Hossain",
      metaDescription: "Custom web applications, SaaS platforms, dashboards and management systems — architected to scale from day one. Next.js, NestJS, PostgreSQL, Docker.",
      keywords: ["full stack development", "SaaS development", "web application", "Next.js developer", "SaaS MVP", "admin dashboard", "custom web app", "full stack developer Bangladesh"],
      geoRegion: "BD-DH",
      geoPlaceName: "Dhaka",
      geoPosition: "23.8103;90.4125",
      geoCountry: "Dhaka, Bangladesh",
      areaServed: "Worldwide",
      availableLanguages: ["en", "bn"],
      faqJson: [
        { question: "How long does it take to build a SaaS MVP?", answer: "A typical SaaS MVP takes 6-12 weeks depending on complexity. I break it into phases: discovery, architecture, development, testing, and deployment — so you can launch early and iterate." },
        { question: "What tech stack do you use for full stack projects?", answer: "I primarily use Next.js + NestJS with PostgreSQL, Docker for containerization, and deploy on Vercel, Railway, or your own VPS. The stack is chosen based on your specific needs." },
        { question: "Do you provide ongoing maintenance after launch?", answer: "Yes. I offer maintenance packages that include bug fixes, feature updates, performance monitoring, and security patches. We can discuss a plan that fits your budget." },
        { question: "Can you work with my existing codebase?", answer: "Absolutely. I regularly work with inherited codebases — I'll audit it first, suggest improvements, and then refactor or extend as needed without disrupting what's already working." },
      ],
      howToSteps: [
        { name: "Discovery Call", text: "We discuss your project goals, target users, technical requirements, and timeline to create a clear roadmap." },
        { name: "Architecture & Design", text: "I design the database schema, API contracts, authentication flow, and UI wireframes for your approval." },
        { name: "Development Sprint", text: "Iterative development with weekly demos. You see progress every week and can provide feedback." },
        { name: "Testing & QA", text: "Automated testing, cross-browser checks, performance optimization, and security review." },
        { name: "Deploy & Handover", text: "Production deployment, environment setup, documentation, and knowledge transfer to your team." },
      ],
      speakableText: "Full stack and SaaS development services by Rasel Hossain. Custom web applications, SaaS platforms, dashboards, and management systems built with Next.js, NestJS, PostgreSQL, and Docker.",
    },
    {
      slug: "ai-integration-automation",
      icon: "ai",
      title: "AI Integration & Automation",
      category: "AI & Automation",
      description: "AI-powered applications, workflow automation, n8n pipelines and intelligent systems that reduce manual work.",
      overview: "AI is only useful when it fits into your actual workflow. I build practical automations — chatbots, document Q&A and n8n pipelines — with human review built in, so the system handles the volume while your team keeps control.",
      order: 2,
      featured: true,
      deliverables: ["AI chatbots & assistants", "n8n & workflow automation", "RAG pipelines & document Q&A", "Human-in-the-loop review flows"],
      stack: ["OpenAI", "n8n", "Supabase", "Python"],
      bestFor: ["Teams buried in manual data entry", "Support teams answering the same questions daily", "Businesses with knowledge locked in documents"],
      features: ["AI chatbots & assistants", "n8n & workflow automation", "RAG pipelines & document Q&A", "Human-in-the-loop automations"],
      metaTitle: "AI Integration & Automation Services | Rasel Hossain",
      metaDescription: "AI-powered applications, workflow automation, n8n pipelines and intelligent systems. Chatbots, RAG pipelines, document Q&A built by Rasel Hossain.",
      keywords: ["AI integration", "workflow automation", "n8n automation", "AI chatbot", "RAG pipeline", "document Q&A", "AI developer Bangladesh", "OpenAI integration"],
      geoRegion: "BD-DH",
      geoPlaceName: "Dhaka",
      geoPosition: "23.8103;90.4125",
      geoCountry: "Dhaka, Bangladesh",
      areaServed: "Worldwide",
      availableLanguages: ["en", "bn"],
      faqJson: [
        { question: "What AI models do you work with?", answer: "I work with OpenAI (GPT-4, DALL-E), Anthropic Claude, open-source models via Ollama, and custom fine-tuned models. I'll recommend the best fit for your use case and budget." },
        { question: "How does n8n workflow automation work?", answer: "n8n is a visual automation tool that connects your apps and services. I build workflows that trigger on events (form submissions, emails, webhooks) and automate tasks across your tools." },
        { question: "Can you build a chatbot for my website?", answer: "Yes. I build AI chatbots trained on your knowledge base that can answer customer questions, escalate to humans when needed, and learn from interactions over time." },
        { question: "What is RAG and do I need it?", answer: "RAG (Retrieval-Augmented Generation) lets AI answer questions using your private documents. If you have docs, manuals, or knowledge bases that need to be searchable by AI, RAG is the solution." },
      ],
      howToSteps: [
        { name: "Identify Use Cases", text: "We map out your manual processes and identify which ones can be automated with AI for maximum ROI." },
        { name: "Data Preparation", text: "I structure your documents, knowledge base, and data sources for AI consumption." },
        { name: "Build & Train", text: "Develop the AI pipeline, chatbot, or automation workflow with proper error handling and human review." },
        { name: "Test & Refine", text: "Test with real scenarios, fine-tune responses, and optimize performance and cost." },
        { name: "Deploy & Monitor", text: "Launch with monitoring dashboards, cost tracking, and ongoing optimization support." },
      ],
      speakableText: "AI integration and automation services by Rasel Hossain. Chatbots, workflow automation with n8n, RAG pipelines, and intelligent systems built with OpenAI, Python, and Supabase.",
    },
    {
      slug: "mobile-app-development",
      icon: "mobile",
      title: "Mobile App Development",
      category: "Mobile",
      description: "Cross-platform Android and iOS apps with React Native, Expo and API-based backends — auth, payments, push and real-time data.",
      overview: "One codebase, both platforms. I build React Native and Expo apps backed by real APIs — with auth, payments, push and offline support — and handle the App Store and Play Store releases for you.",
      order: 3,
      featured: false,
      deliverables: ["React Native / Expo cross-platform app", "Auth, payments & push notifications", "Offline & real-time sync", "App Store & Play Store release"],
      stack: ["React Native", "Expo", "Node.js", "PostgreSQL"],
      bestFor: ["Businesses that need a real mobile presence", "Existing web products going mobile", "Startups shipping an MVP to both stores"],
      features: ["React Native & Expo apps", "Auth, payments & push", "Offline & real-time sync", "App Store & Play releases"],
      metaTitle: "Mobile App Development Services | Rasel Hossain",
      metaDescription: "Cross-platform Android and iOS apps with React Native and Expo. Auth, payments, push notifications, and App Store releases by Rasel Hossain.",
      keywords: ["mobile app development", "React Native developer", "Expo app", "cross-platform mobile", "iOS Android app", "mobile developer Bangladesh", "React Native Bangladesh"],
      geoRegion: "BD-DH",
      geoPlaceName: "Dhaka",
      geoPosition: "23.8103;90.4125",
      geoCountry: "Dhaka, Bangladesh",
      areaServed: "Worldwide",
      availableLanguages: ["en", "bn"],
      faqJson: [
        { question: "React Native vs native — which should I choose?", answer: "React Native is ideal for most apps since you get one codebase for both platforms. I recommend native only if you need platform-specific features like advanced AR/VR or very performance-critical UIs." },
        { question: "How much does it cost to build a mobile app?", answer: "Costs vary based on complexity. A simple MVP can start from $3,000-5,000, while a full-featured app with payments, push, and admin panel typically ranges from $8,000-20,000." },
        { question: "Do you handle App Store and Play Store submissions?", answer: "Yes. I handle the entire submission process including screenshots, descriptions, privacy policies, and compliance review for both stores." },
        { question: "Can you add offline support?", answer: "Yes. I implement local storage with SQLite or AsyncStorage, sync queues, and conflict resolution so your app works reliably without internet." },
      ],
      howToSteps: [
        { name: "App Strategy", text: "Define your app's core features, target platforms, and technical architecture." },
        { name: "UI/UX Design", text: "Design mobile-first interfaces with platform-specific patterns (iOS HIG, Material Design)." },
        { name: "Cross-platform Build", text: "Develop with React Native and Expo for efficient, maintainable code across both platforms." },
        { name: "Backend Integration", text: "Connect to APIs, implement auth, payments, push notifications, and real-time features." },
        { name: "Store Submission", text: "Prepare store listings, handle review processes, and launch on both App Store and Play Store." },
      ],
      speakableText: "Mobile app development services by Rasel Hossain. Cross-platform Android and iOS apps built with React Native, Expo, Node.js, and PostgreSQL.",
    },
    {
      slug: "ecommerce-headless",
      icon: "commerce",
      title: "E-commerce & Headless",
      category: "E-commerce",
      description: "Fast, SEO-friendly commerce experiences with Next.js — including headless WordPress, Shopify and WooCommerce setups.",
      overview: "A storefront that loads fast, ranks on Google and converts. I build headless commerce with Next.js on top of Shopify, WooCommerce or WordPress — plus custom checkout, payments and inventory tooling that fits your operation.",
      order: 4,
      featured: false,
      deliverables: ["Fast SEO storefront with Next.js", "Headless Shopify / WooCommerce / WordPress", "Custom checkout & payment flows", "Inventory & admin tooling"],
      stack: ["Next.js", "Shopify", "WooCommerce", "Stripe"],
      bestFor: ["Stores outgrowing slow template themes", "Brands selling across multiple channels", "Merchants who need custom inventory flows"],
      features: ["Fast SEO-friendly storefronts", "Headless WordPress & Shopify", "WooCommerce customizations", "Payments, carts & checkout"],
      metaTitle: "E-commerce & Headless Development Services | Rasel Hossain",
      metaDescription: "Fast, SEO-friendly e-commerce with Next.js. Headless Shopify, WooCommerce, WordPress setups with custom checkout and payments by Rasel Hossain.",
      keywords: ["e-commerce development", "headless commerce", "Shopify developer", "WooCommerce", "Next.js ecommerce", "headless WordPress", "e-commerce developer Bangladesh"],
      geoRegion: "BD-DH",
      geoPlaceName: "Dhaka",
      geoPosition: "23.8103;90.4125",
      geoCountry: "Dhaka, Bangladesh",
      areaServed: "Worldwide",
      availableLanguages: ["en", "bn"],
      faqJson: [
        { question: "What is headless commerce?", answer: "Headless commerce separates the frontend (what customers see) from the backend (inventory, orders, payments). This gives you faster load times, better SEO, and full design control while keeping your existing backend." },
        { question: "Which platform is best — Shopify or WooCommerce?", answer: "Shopify is easier to manage and scales well. WooCommerce gives you more control and is cheaper for large catalogs. I'll help you choose based on your products, budget, and technical needs." },
        { question: "How do you improve e-commerce SEO?", answer: "I implement server-side rendering, structured data (Product schema), optimized images, fast Core Web Vitals, clean URLs, and proper meta tags — all critical for e-commerce rankings." },
        { question: "Can you integrate with my existing payment gateway?", answer: "Yes. I integrate with Stripe, bKash, Nagad, SSLCommerz, and most regional gateways. I also handle multi-currency and subscription billing." },
      ],
      howToSteps: [
        { name: "Audit & Strategy", text: "Analyze your current store, identify performance bottlenecks, and plan the headless migration." },
        { name: "Architecture Design", text: "Design the frontend, API layer, and data flow between your commerce backend and the new storefront." },
        { name: "Frontend Build", text: "Develop a fast, SEO-optimized Next.js storefront with product pages, cart, and checkout." },
        { name: "Backend Integration", text: "Connect to Shopify, WooCommerce, or custom APIs for inventory, orders, and payments." },
        { name: "Launch & Optimize", text: "Deploy, monitor Core Web Vitals, and optimize conversions with analytics." },
      ],
      speakableText: "E-commerce and headless development services by Rasel Hossain. Fast, SEO-friendly storefronts built with Next.js, Shopify, WooCommerce, and Stripe.",
    },
    {
      slug: "crm-erp-business-software",
      icon: "crm",
      title: "CRM, ERP & Business Software",
      category: "Business Software",
      description: "Business-first software: CRM, ERP, HR, inventory, school management and LMS platforms designed around your workflow.",
      overview: "When off-the-shelf software doesn't match how your business works, I build the system that does. Role-based dashboards, automated reporting and clean data models — so the whole team works from one source of truth.",
      order: 5,
      featured: false,
      deliverables: ["CRM / ERP platforms", "HR, inventory & LMS systems", "Role & permission design", "Reports & analytics modules"],
      stack: ["Next.js", "NestJS", "PostgreSQL", "Redis"],
      bestFor: ["Schools, hospitals & agencies with unique flows", "Teams juggling multiple disconnected tools", "Organizations needing role-based access & reporting"],
      features: ["CRM & ERP platforms", "HR, inventory & LMS systems", "School & business management", "Workflow & permission design"],
      metaTitle: "CRM, ERP & Business Software Development | Rasel Hossain",
      metaDescription: "Custom CRM, ERP, HR, inventory, school management and LMS platforms. Business-first software designed around your workflow by Rasel Hossain.",
      keywords: ["CRM development", "ERP software", "business software", "school management system", "LMS development", "HR software", "inventory management", "business software developer Bangladesh"],
      geoRegion: "BD-DH",
      geoPlaceName: "Dhaka",
      geoPosition: "23.8103;90.4125",
      geoCountry: "Dhaka, Bangladesh",
      areaServed: "Worldwide",
      availableLanguages: ["en", "bn"],
      faqJson: [
        { question: "How is custom CRM different from Salesforce or HubSpot?", answer: "Custom CRM is built around your exact workflow — no paying for features you don't use, no workarounds for features you need but don't have. You own the code and control the costs." },
        { question: "Can you integrate with existing tools?", answer: "Yes. I integrate with popular tools via APIs — payment gateways, email services, accounting software, government portals, and more." },
        { question: "How do you handle data security?", answer: "I implement role-based access control, encryption at rest and in transit, audit logs, and regular backups. For healthcare/finance, I follow industry-specific compliance requirements." },
        { question: "Do you build school management systems?", answer: "Yes. I build complete school/college management systems with student enrollment, attendance, grading, fee management, parent portals, and teacher dashboards." },
      ],
      howToSteps: [
        { name: "Process Mapping", text: "Document your current workflows, pain points, and requirements through stakeholder interviews." },
        { name: "System Design", text: "Design the database schema, user roles, permissions, and module architecture." },
        { name: "Iterative Build", text: "Build module by module with user feedback at each stage — starting with the highest-impact features." },
        { name: "Data Migration", text: "Import existing data from spreadsheets, old systems, or other tools with validation and cleanup." },
        { name: "Training & Support", text: "Provide user training, admin documentation, and ongoing support for bug fixes and enhancements." },
      ],
      speakableText: "CRM, ERP and business software development by Rasel Hossain. Custom business systems including school management, HR, inventory, and LMS platforms built with Next.js, NestJS, and PostgreSQL.",
    },
    {
      slug: "devops-deployment",
      icon: "devops",
      title: "DevOps & Deployment",
      category: "DevOps",
      description: "From dev to production: Ubuntu VPS, Docker, Nginx, Cloudflare, SSL, domain setup and production monitoring.",
      overview: "From a local build to a stable production server. I set up Ubuntu VPS, Docker, Nginx, SSL and Cloudflare, wire up CI/CD so deploys are one click, and add monitoring and backups so nothing goes unnoticed.",
      order: 6,
      featured: false,
      deliverables: ["Ubuntu VPS & Docker setup", "Nginx, SSL & Cloudflare", "CI/CD with GitHub Actions", "Monitoring, backups & security"],
      stack: ["Linux", "Docker", "Nginx", "GitHub Actions"],
      bestFor: ["Projects stuck in localhost", "Apps that need zero-downtime deploys", "Teams that want visibility into production"],
      features: ["Ubuntu VPS & Docker setup", "Nginx, SSL & Cloudflare", "CI/CD with GitHub Actions", "Monitoring & backups"],
      metaTitle: "DevOps & Deployment Services | Rasel Hossain",
      metaDescription: "Ubuntu VPS, Docker, Nginx, Cloudflare, SSL setup and CI/CD with GitHub Actions. Production deployment and monitoring by Rasel Hossain.",
      keywords: ["DevOps engineer", "VPS setup", "Docker deployment", "Nginx configuration", "CI/CD pipeline", "production deployment", "server management", "DevOps engineer Bangladesh"],
      geoRegion: "BD-DH",
      geoPlaceName: "Dhaka",
      geoPosition: "23.8103;90.4125",
      geoCountry: "Dhaka, Bangladesh",
      areaServed: "Worldwide",
      availableLanguages: ["en", "bn"],
      faqJson: [
        { question: "What does DevOps setup include?", answer: "Full production setup: server provisioning, Docker containers, Nginx reverse proxy, SSL certificates, Cloudflare DNS, CI/CD pipelines, monitoring dashboards, and automated backups." },
        { question: "How much does VPS hosting cost?", answer: "Depends on your needs. A basic VPS starts at $5-10/month (DigitalOcean, Vultr). I'll recommend the right plan based on your traffic and app requirements." },
        { question: "Can you set up CI/CD for my existing project?", answer: "Yes. I configure GitHub Actions or GitLab CI for automated testing, building, and deployment. Push to main = deploy to production, with zero downtime." },
        { question: "Do you offer ongoing server management?", answer: "Yes. I offer server management packages including security updates, monitoring, backup verification, performance optimization, and incident response." },
      ],
      howToSteps: [
        { name: "Infrastructure Audit", text: "Review your current setup, identify issues, and plan the production architecture." },
        { name: "Server Setup", text: "Provision VPS, configure firewall, SSH access, user accounts, and security hardening." },
        { name: "Containerization", text: "Containerize your application with Docker, set up Docker Compose for multi-service apps." },
        { name: "CI/CD Pipeline", text: "Configure automated build, test, and deploy pipelines with GitHub Actions or GitLab CI." },
        { name: "Monitor & Maintain", text: "Set up uptime monitoring, log aggregation, automated backups, and alerting." },
      ],
      speakableText: "DevOps and deployment services by Rasel Hossain. Ubuntu VPS, Docker, Nginx, Cloudflare, SSL, CI/CD with GitHub Actions, and production monitoring.",
    },
  ];

  for (const service of services) {
    await prisma.service.upsert({
      where: { slug: service.slug },
      update: service,
      create: service,
    });
  }
  console.log("✅ Services seeded");

  console.log("🎉 Seeding complete!");
}

main()
  .catch((e) => {
    console.error("❌ Seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
